# Generated by Django 4.1.5 on 2024-01-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userbase_address_line_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='full_name',
        ),
    ]
