# Generated by Django 4.1.5 on 2024-06-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_address_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(max_length=255, verbose_name='Address Line 2'),
        ),
    ]
