# Generated by Django 4.1.5 on 2023-04-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_image_image'),
        ('store', '0004_product_description_alter_image_image'),
    ]

    operations = [
    ]
